# -*- coding: utf-8 -*-
"""Signal_significance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tTlSLLzH1RYB3bISHbdaGSrnGF2dd3Qw

**How many events I need to have a 3, 4 or 5σ evidence?**
"""

import numpy as np
import matplotlib.pyplot as plt
# s/ sqrt (S+B) = n sigma
# max number of signal events
nSig_max =50
nBKG =500
for n in range(3,6):
    f = lambda x: (n*n+np.sqrt(n*n+4*n*x))/2
    xi=0
    xf=1000
    point=100
    x = np.linspace(xi,xf,point)
    y= f(x)
    SIG_MIN= f(nBKG)
    plt.plot(x, y, label="S= " + str(n) + r" $ \sigma $ ")
    plt.xlabel("B")
    plt.ylabel("S")
    plt.title(r"$n\sigma = \frac{S}{\sqrt{S+B}}$")
    n=n+1
    plt.legend()
    print(fr"Signal Estimation - S = {SIG_MIN:.1f} for B = {nBKG} and n= {n}")

plt.plot([nBKG,nBKG], [0,f(xf)], linestyle='dotted')
plt.show()

"""**How many background events I can have at maximum to have nσ with N signal events?**"""

nSig_max = 60
for n in range(3,6):
    finv = lambda sig: (((sig**2)/n**2)-sig)
    sig_i=0
    sig_f=100
    point=100
    sig = np.linspace(sig_i,sig_f,point)
    BKG = finv(sig)
    plt.plot(sig ,BKG,label=str(n)+r"$ \sigma$ ")
    plt.xlabel("S")
    plt.ylabel("B")
    plt.title(r"$B=\frac{S^2}{n^2} -S$")

    BKG = finv(nSig_max)
    print(fr"Background Estimation - B = {BKG:.1f} for Signal S= {nSig_max} and n= {n}")

    n=n+1
    plt.legend()

plt.xticks(np.arange(0,100,10))
plt.yticks(np.arange(0,1000,100))
plt.plot( [nSig_max,nSig_max], [0,1000], linestyle='dotted')
plt.show()